const BAD_REQUEST_STATUS_CODE = 400;
const INTERNAL_SERVER_ERROR = 500;
const ITEM_NOT_FOUND = 404;
const CREATED = 201;
const REQUEST_STATUS_OK = 200;
const REQUEST_COMPLETED = 204;
404;
module.exports = {
  BAD_REQUEST_STATUS_CODE,
  INTERNAL_SERVER_ERROR,
  CREATED,
  REQUEST_STATUS_OK,
  ITEM_NOT_FOUND,
  REQUEST_COMPLETED,
};
