const BAD_REQUEST_STATUS_CODE = 400;
const INTERNAL_SERVER_ERROR = 500;
const CREATED = 201;
const REQUEST_STATUS_OK = 200;

module.exports = {
  BAD_REQUEST_STATUS_CODE,
  INTERNAL_SERVER_ERROR,
  CREATED,
  REQUEST_STATUS_OK,
};
